### ISSUE TITLE
Unable to run multiple GraphQLGenerateClientTask tasks

### ISSUE THREAD

**Issue by rbraeunlich** [ExpediaGroup/graphql-kotlin#1026]
**Library Version**
4.0.0-alpha11

**Describe the bug**
Hi everyone,
after updating my project from 4.0.0-alpha10 to 4.0.0-alpha11 I get this error from Gradle:
```
Caused by: java.lang.NoClassDefFoundError: com.expediagroup.graphql.plugin.client.generator.GraphQLClientType
	at com.expediagroup.graphql.plugin.gradle.actions.GenerateClientAction.execute(GenerateClientAction.kt:37)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
	at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory$1.lambda$execute$0(IsolatedClassloaderWorkerFactory.java:58)
	at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory$1$$Lambda$1663/0000000088008CC0.execute(Unknown Source)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$$Lambda$126/0000000000000000.apply(Unknown Source)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory$1.execute(IsolatedClassloaderWorkerFactory.java:50)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
	at org.gradle.workers.internal.DefaultWorkerExecutor$$Lambda$1031/0000000000000000.call(Unknown Source)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:214)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.expediagroup.graphql.plugin.client.generator.GraphQLClientType
	... 33 more
```

Looking at the changes, I can see that this commit https://github.com/ExpediaGroup/graphql-kotlin/commit/8889faf4874ca08197f7ee65850db63a0adeff2a introduced the `GenerateClientAction` class. Anyways, it imports `com.expediagroup.graphql.plugin.client.generator.GraphQLClientType` instead of `com.expediagroup.graphql.plugin.gradle.config.GraphQLClientType`
**To Reproduce**
Steps to reproduce the behavior. Please provide:
I have those tasks in my build.gradle.kts (anonymised the code a little):
```
val generateSomeClient = tasks.register<GraphQLGenerateClientTask>("generateSomeClient")
generateSomeClient {
    packageName.set("com.promaterial.some.network.graphql")
    schemaFileName.set("src/main/resources/some.dev.schema.graphql")
    clientType.set(GraphQLClientType.WEBCLIENT)
    allowDeprecatedFields.set(true)
    queryFileDirectory.set("src/main/resources/some")
    outputDirectory.set(File(generatedSourcesPath))
}

val generateAnotherClient = tasks.register<GraphQLGenerateClientTask>("generateAnotherClient")
generateAnotherClient {
    packageName.set("com.promaterial.another.network.graphql")
    schemaFileName.set("src/main/resources/another.dev.schema.graphql")
    clientType.set(GraphQLClientType.WEBCLIENT)
    allowDeprecatedFields.set(true)
    queryFileDirectory.set("src/main/resources/another")
    outputDirectory.set(File(generatedSourcesPath))
}
```
In the build.gradle.kts I already import `com.expediagroup.graphql.plugin.gradle.config.GraphQLClientType`
**Expected behavior**
I guess the imports should be adjusted in the class.

**Comment by dariuszkuc** [comment]
Hello 👋 
Thanks for raising this but it appears it might be a classpath issue in your build. Can you provide a sample GH project that reproduces this error?

In `alpha11` [GenerateClientAction](https://github.com/ExpediaGroup/graphql-kotlin/blob/4.0.0-alpha.11/plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/actions/GenerateClientAction.kt#L37) performs a mapping between `com.expediagroup.graphql.plugin.gradle.config.GraphQLClientType` from [GenerateClientParameters](https://github.com/ExpediaGroup/graphql-kotlin/blob/4.0.0-alpha.11/plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/parameters/GenerateClientParameters.kt#L19) to `com.expediagroup.graphql.plugin.client.generator.GraphQLClientType` that is used by the client generator. We have duplicate enum there so Gradle plugin won't need the extra dependency which is dynamically added just for the client generation tasks.

**Comment by rbraeunlich** [comment]
Hi @dariuszkuc 
thanks for getting back to me. I create this project https://github.com/rbraeunlich/graphql-kotlin-bug-example and it runs into the same problem. Running `./gradlew build` will run into the NoClassDefFound error. To me the setup looks correct. I have the plugin and the implementation dependency present.

**Comment by dariuszkuc** [comment]
Thanks for the repro! It appears that there is some issue with the plugin configuration and the task dependency order, i.e. if you remove this line -> https://github.com/rbraeunlich/graphql-kotlin-bug-example/blob/main/build.gradle.kts#L49 it will work (well it complains about spring boot plugin misconfiguration but after fixing spring boot plugin config it works).

```groovy
tasks.compileKotlin {
    dependsOn(generateGraphQLClient) // <<<<<< causes error
    kotlinOptions {
        jvmTarget = "11"
    }
}
```

I fixed some of our configurations in #1028 but it does not resolve the above issue. Still looking into this.

**Comment by dariuszkuc** [comment]
So the underlying issue is the build file misconfiguration. Reason why your `generateClient` task cannot resolve the dependency is that you [create new custom task](https://github.com/rbraeunlich/graphql-kotlin-bug-example/blob/main/build.gradle.kts#L23) instead of retrieving existing task (which configures custom configuration classpath and also adds explicit dependency on compile task),

```
val generateGraphQLClient = tasks.register<GraphQLGenerateClientTask>("generateGraphQLClient")
generateGraphQLClient { ... }

// vs
val graphqlGenerateClient by tasks.getting(GraphQLGenerateClientTask::class) { ... }
```

See [wiki](https://expediagroup.github.io/graphql-kotlin/docs/plugins/gradle-plugin-examples) for some example use cases

**Comment by rbraeunlich** [comment]
Hey @dariuszkuc 
thank you for investigating this. Still, I wonder, how can I generate two clients when not creating new tasks?
My application has to talk to two different GraphQL API. Therefore we create the "generateSomeClient" and "generateAnotherClient" tasks.

**Comment by dariuszkuc** [comment]
My PR https://github.com/ExpediaGroup/graphql-kotlin/pull/1028 addresses the classpath issue of multiple client tasks. I've updated this issue title to reflect this.

**Comment by dariuszkuc** [comment]
I think this change https://github.com/ExpediaGroup/graphql-kotlin/pull/1028/commits/7b00ac8e54ab4b97b6bfd22aaccf6a1c64a4f418 should apply default conventions on all generate client types.

**Comment by rbraeunlich** [comment]
Ok, cool, looking forward to the merge and release of your PR :+1:
